name: Build EXE with PyInstaller (No Actions Used)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      run: |
        git clone ${{ github.repositoryUrl }} .
    
    - name: Set up Python
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile --name=opcua_exporter exporter.py

    - name: Archive EXE to zip
      run: Compress-Archive -Path dist\opcua_exporter.exe -DestinationPath opcua_exporter.zip

    - name: Print base64 to logs
      run: |
        $bytes = [System.IO.File]::ReadAllBytes("opcua_exporter.zip")
        $encoded = [Convert]::ToBase64String($bytes)
        Set-Content -Path opcua_exporter_b64.txt -Value $encoded
        Get-Content opcua_exporter_b64.txt
